spring:
  application:
    name: ptmonitor
server:
  port: 3303

logging:
  file: logs/ptmonitor.log
  level:
    org.springframework.boot.autoconfigure: ERROR
    com.sfmotors.cloud.ptmonitor: TRACE
  pattern.console:

ptmonitor:
  config:
    ptcan: ptmessage.json
    signame: sigtable.properties


cloud:
  alicloud: http://10.21.62.52:5000/upload